WIDTH, HEIGHT = 700, 480

X_WALL, Y_WALL = .9 * WIDTH / 2, .9 * HEIGHT / 2

ALIGN = 'center'
FONT = ('Arial', 20, 'normal')

GAME_SPEED = .001

BALL_SPEED = 5
BALL_PLAYER_DIST = 40

PLAYER_SPEED = 50
